### ISSUE TITLE
Create tickets for CP UI updates from design review

### ISSUE THREAD

**Issue by bbodine1** [ideacrew/enroll-fe#74]
Break out tickets for updates needed based on Alex R's review of current carrier portal UI.

https://www.pivotaltracker.com/n/projects/2640059/stories/186018401

[Figma](https://www.figma.com/file/E0twjR79i5SdcnrhHkZkz3/Carrier-Portal?type=design&node-id=2308%3A49608&mode=design&t=XWqGOq4IdGxGWL6X-1)

```[tasklist]
### Tasks
- [ ] https://github.com/ideacrew/enroll-fe/issues/75
- [ ] https://github.com/ideacrew/enroll-fe/issues/76
- [ ] https://github.com/ideacrew/enroll-fe/issues/77
- [ ] https://github.com/ideacrew/enroll-fe/issues/78
- [ ] https://github.com/ideacrew/enroll-fe/issues/79
```

**Comment by bbodine1** [comment]
![image](https://github.com/ideacrew/enroll-fe/assets/2924609/50ec79dc-4c25-41ab-85cf-d257624986bf)
